language: java
deploy:
   edge: true
   provider: cloudfoundry
   username: a-premkumar
   password: Alohomora!1
   api: https://api.run.pivotal.io
   organization: VZWHackathon_ACSSSupportTeam
   space: development